### 实际证明product的操作表示张量积！！！

In [1]:
import numpy as np
a = np.random.rand(3)
b = np.random.rand(3)
c = np.random.rand(3)

In [2]:
d = np.einsum("i,j,k->ijk",a,b,c)
print("shape of d is; ",d.shape)
print("the output of tensor product is: ",d, end='\n')

shape of d is;  (3, 3, 3)
the output of tensor product is:  [[[0.03480168 0.02727637 0.00152967]
  [0.0581001  0.04553688 0.00255373]
  [0.0448311  0.0351371  0.0019705 ]]

 [[0.12739382 0.09984695 0.00559946]
  [0.21267923 0.16669076 0.0093481 ]
  [0.1641072  0.12862165 0.00721316]]

 [[0.12362948 0.09689659 0.00543401]
  [0.2063948  0.16176524 0.00907187]
  [0.15925802 0.12482103 0.00700002]]]


In [3]:
from itertools import product
res = np.ones((3,3,3))
for i,j,k in product(range(3),range(3),range(3)):
    res[i,j,k] = a[i] * b[j] * c[k]
print('another d caculation result is: ',res)

another d caculation result is:  [[[0.03480168 0.02727637 0.00152967]
  [0.0581001  0.04553688 0.00255373]
  [0.0448311  0.0351371  0.0019705 ]]

 [[0.12739382 0.09984695 0.00559946]
  [0.21267923 0.16669076 0.0093481 ]
  [0.1641072  0.12862165 0.00721316]]

 [[0.12362948 0.09689659 0.00543401]
  [0.2063948  0.16176524 0.00907187]
  [0.15925802 0.12482103 0.00700002]]]


In [4]:
res == d

array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

看到一堆True了吧，两重计算方法的结果是完全相同的

### 下面将更清晰的复现代码里的操作

In [11]:
a = np.random.rand(2,3)
b = np.random.rand(2,3)
c = np.random.rand(2,3)
d = np.random.rand(2,3)
res = np.einsum("pi,pj,pk,pm->pijkm",a,b,c,d)
print("result shape is: ",res.shape)
print(res)

result shape is:  (2, 3, 3, 3, 3)
[[[[[1.91624704e-01 1.48037784e-01 3.84463130e-02]
    [2.14108564e-01 1.65407470e-01 4.29573259e-02]
    [1.31920720e-02 1.01914057e-02 2.64677005e-03]]

   [[3.71815441e-01 2.87242369e-01 7.45985904e-02]
    [4.15441582e-01 3.20945316e-01 8.33514507e-02]
    [2.55969923e-02 1.97747051e-02 5.13561119e-03]]

   [[3.18713108e-01 2.46218683e-01 6.39444895e-02]
    [3.56108604e-01 2.75108206e-01 7.14472745e-02]
    [2.19412538e-02 1.69505002e-02 4.40214801e-03]]]


  [[[3.20953856e-01 2.47949750e-01 6.43940583e-02]
    [3.58612265e-01 2.77042385e-01 7.19495925e-02]
    [2.20955142e-02 1.70696726e-02 4.43309779e-03]]

   [[6.22756862e-01 4.81104700e-01 1.24945817e-01]
    [6.95826659e-01 5.37554054e-01 1.39606058e-01]
    [4.28726212e-02 3.31208226e-02 8.60167909e-03]]

   [[5.33815310e-01 4.12393777e-01 1.07101172e-01]
    [5.96449346e-01 4.60781087e-01 1.19667651e-01]
    [3.67495936e-02 2.83905377e-02 7.37319534e-03]]]


  [[[3.42297951e-01 2.64438922e-

In [14]:
ano_res = np.zeros((2,3,3,3,3))
bond = 3
for i,j,k,l in product(range(bond),range(bond),range(bond),range(bond)):
    ano_res[:,i,j,k,l] = a[:,i] * b[:,j] * c[:,k] * d[:,l]
print("result shape is: ",ano_res.shape)
print(ano_res)

result shape is:  (2, 3, 3, 3, 3)
[[[[[1.91624704e-01 1.48037784e-01 3.84463130e-02]
    [2.14108564e-01 1.65407470e-01 4.29573259e-02]
    [1.31920720e-02 1.01914057e-02 2.64677005e-03]]

   [[3.71815441e-01 2.87242369e-01 7.45985904e-02]
    [4.15441582e-01 3.20945316e-01 8.33514507e-02]
    [2.55969923e-02 1.97747051e-02 5.13561119e-03]]

   [[3.18713108e-01 2.46218683e-01 6.39444895e-02]
    [3.56108604e-01 2.75108206e-01 7.14472745e-02]
    [2.19412538e-02 1.69505002e-02 4.40214801e-03]]]


  [[[3.20953856e-01 2.47949750e-01 6.43940583e-02]
    [3.58612265e-01 2.77042385e-01 7.19495925e-02]
    [2.20955142e-02 1.70696726e-02 4.43309779e-03]]

   [[6.22756862e-01 4.81104700e-01 1.24945817e-01]
    [6.95826659e-01 5.37554054e-01 1.39606058e-01]
    [4.28726212e-02 3.31208226e-02 8.60167909e-03]]

   [[5.33815310e-01 4.12393777e-01 1.07101172e-01]
    [5.96449346e-01 4.60781087e-01 1.19667651e-01]
    [3.67495936e-02 2.83905377e-02 7.37319534e-03]]]


  [[[3.42297951e-01 2.64438922e-

In [15]:
res == ano_res

array([[[[[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]]],


        [[[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]]],


        [[[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]],

         [[ True,  True,  True],
          [ True,  True,  True],
          [ True,  True,  True]]]],



       [[[[ True,  True,  True],
          [ True,  True,  True],
          [ True,

结果一样